### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by renuka-srishti** [airavata-courses/vulcan#25]
UI of your project is really impressive. Very nice work on fronted.

Thanks,
Team Viyad

**Comment by renuka-srishti** [comment]
![Vulcan](https://user-images.githubusercontent.com/23609304/153337362-c8e6d5f9-b094-4108-b785-55406ab81c63.jpeg)
 Nice work, thought to share :)

**Comment by Akshace** [comment]
Closing Issue,
