### ISSUE TITLE
[P2] Containerization 

### ISSUE THREAD

**Issue by ratchahan-anbarasan** [airavata-courses/vulcan#30]
- Dockerize currently implemented microservices
- Analyze how the communication across multiple containers works
- Analyze on how to get the containers posted to DockerHub

**Comment by ratchahan-anbarasan** [comment]
@amberramesh 
@Akshace 

I am having trouble setting up communication between kafka containers and our microservices containers. Kafka Containers are turning up smoothly as expected. Our microservices are failing since the consumer client in the service is not able to establish a connection with the kafka.

**Comment by amberramesh** [comment]
> @amberramesh @Akshace
> 
> I am having trouble setting up communication between kafka containers and our microservices containers. Kafka Containers are turning up smoothly as expected. Our microservices are failing since the consumer client in the service is not able to establish a connection with the kafka.

This issue has been addressed by services updates in https://github.com/airavata-courses/vulcan/issues/41, https://github.com/airavata-courses/vulcan/issues/42, https://github.com/airavata-courses/vulcan/issues/43, https://github.com/airavata-courses/vulcan/issues/44 and https://github.com/airavata-courses/vulcan/issues/45
